### ISSUE TITLE
Research Java RMI and understand how to implement it for our purpose.

### ISSUE THREAD

**Issue by vishek23** [julian-dsilva-92/se_csv_project#24]
We will implement this to authenticate user logins and provide permissions.

**Comment by kpatel182** [comment]
Implement the server. A "server" class, in this context, is the class which has a main method that creates an instance of the remote object implementation, exports the remote object, and then binds that instance to a name in a Java RMI registry. ... Register the remote object with a Java RMI registry.

**Comment by gloriakim270** [comment]
https://www.oracle.com/technetwork/java/javase/tech/index-jsp-138781.html
This website explains what Java RMI is and its advantages. It also gives sample code on how to implement if for our purposes.
