### ISSUE TITLE
CSV FILE to front end by using java RMI maybe? 

### ISSUE THREAD

**Issue by julian-dsilva-92** [julian-dsilva-92/se_csv_project#30]

**Comment by vishek23** [comment]
Verified step by step procedure (Either server or client)

http://www.ejbtutorial.com/java-rmi/how-to-transfer-or-copy-a-file-between-computers-using-java-rmi

**Comment by vishek23** [comment]
Biggest issue is that the other groups have not been able to implement Java RMI properly yet
