### ISSUE TITLE
Polling 

### ISSUE THREAD

**Issue by julian-dsilva-92** [julian-dsilva-92/se_csv_project#49]
Create a method or a pseudo code method on how we can do polling. Work with the backend.

**Comment by j-copp1** [comment]
Polling method needs to be enclosed by try/catch statement in order to catch any exceptions thrown by the server object

Simple polling statement would be:

Calling a method poll() inside a while loop and use thread.sleep(<number of millis>) to wait between invocations.


//wait and check every 1 second 
		while(conditionBoolean == false) {
			try {
				//display polling icon
				Thread.sleep(1000);	
				
			} catch (Exception e) {
			}
		}
		//then do action

**Comment by vishek23** [comment]
import java.sql.*;

public class pollingResults {
   public static void main(String[] args) {
      try {Class.forName("org.apache.derby.jdbc.ClientDriver");} 
      catch(ClassNotFoundException e) 
      {
         System.out.println("Class not found "+ e);
      }
      try {
         Connection con = DriverManager.getConnection(
            "jdbc:derby://localhost:1527/testDb","blank", "blank");
         
         Statement stmt = con.createStatement();
         ResultSet rs = stmt.executeQuery("SELECT * FROM               ");
         System.out.println("id                         ");
         
         while (rs.next()) {
            int id = rs.getInt("id");
            String name = rs.getString("name");
            String job = rs.getString("job");
            System.out.println(id+"   "+name+"    "+job);
         }
      } catch(SQLException e) {
         System.out.println("SQL exception occured" + e);
      }
   }
}
